name: Regist issue
on:
  issues:
    types: [opened]
jobs:
  regist:
    runs-on: ubuntu-latest
    permissions:
      issues: write
#     steps:
#       - name: Get source
#         uses: actions/checkout@v2
#       - name: Add comment
#         uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
#         with:
#           issue-number: ${{ github.event.issue.number }}
#           body: |
#             어떤 문제인지 확인중이에요. 확인되면 알려드릴게요!
